[package]
name = "bfi"
version = "0.1.0"
edition = "2018"
authors = ["Yusaku Hashimoto <nonowarn@gmail.com>"]
license = "MIT"
description = "Brainfuck interpreter"
homepage = "https://github.com/nonowarn/bfi"
repository = "https://github.com/nonowarn/bfi"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
clap = "2.33.3"
